pop-up-html-css
Morifer79/code-jedi-project-02 pull request #5
Opened 2023-08-04 12:54 UTC by THafinchuk

2023-08-04 15:25 UTC, Morifer79 requested changes

2023-08-04 15:25 UTC, Morifer79 commented on src/css/pop-up.css
> +    --tran: 250ms cubic-bezier(0.4, 0, 0.2, 1);
В style.css уже есть переменная для транзишина... она не подходит?

2023-08-04 15:25 UTC, Morifer79 commented on src/css/pop-up.css
> +    transition: opacity var(--tran), visibility: var(--tran);
После visibility не нужно двоеточие.
У тебя даже vsc подчёркивает ошибку

2023-08-04 15:25 UTC, Morifer79 commented on src/css/pop-up.css
> +    transition: opacity var(--tran); visibility: var(--tran); transform: var(--tran); scale: var(--tran);
Перечисление идёт через запятую, а не точку с запятой

2023-08-04 15:25 UTC, Morifer79 commented on src/css/pop-up.css
> +        transition: color: var(--tran);
здесь тоже после color не нужно двоеточия

2023-08-04 15:25 UTC, Morifer79 commented on src/css/pop-up.css
> +        color: #B4AFAF;
я недавно добавил переменную с этим цветом - подставь её

2023-08-04 15:30 UTC, THafinchuk commented on src/css/pop-up.css
> +    --tran: 250ms cubic-bezier(0.4, 0, 0.2, 1);
в мене чомусь вони не відображаються, хоча і постійно стараюся оновлювати

2023-08-06 20:29 UTC, Morifer79 requested changes

2023-08-06 20:29 UTC, Morifer79 commented on src/css/pop-up.css
> +    background-color: rgba(17, 17, 17, 0.40);
синтаксис
background-color: rgba(17, 17, 17, .4);

2023-08-06 20:29 UTC, Morifer79 commented on src/css/pop-up.css
> +    transition: opacity var(--tran), visibility var(--tran);
транзишн берём с рута style.css
--transition

2023-08-06 20:29 UTC, Morifer79 commented on src/css/pop-up.css
> +@media screen and (min-width: 375px) and (max-width: 767px) {
не вдавался в логику, но ты уверена что нужна именно такая запись?
может max 375 и min 768 ? (если нужны два разных диапазона)
потому что в данный момент у тебя и написано неправильно, и действовать будет банально - просто  до 767, а в таком случае непонятно, зачем вообще min 375.

2023-08-06 20:29 UTC, Morifer79 commented on src/css/pop-up.css
> +        color: #111;
замени на переменную с style.css

2023-08-06 20:29 UTC, Morifer79 commented on src/css/pop-up.css
> +        color: #4F2EE8;
замени на переменную с style.css

2023-08-06 20:29 UTC, Morifer79 commented on src/css/pop-up.css
> +        filter: drop-shadow(0px 3px 3px rgba(0, 0, 0, 0.15));
синтаксис 
filter: drop-shadow(0 3px 3px rgba(0, 0, 0, .15));

2023-08-06 20:29 UTC, Morifer79 commented on src/css/pop-up.css
> +        border: 2px solid #4F2EE8;
переменную для цвета берём с style.css

2023-08-06 20:29 UTC, Morifer79 commented on src/css/pop-up.css
> +        background-color: #4F2EE8;
переменную для цвета берём с style.css

2023-08-06 20:29 UTC, Morifer79 commented on src/js/pop-up.js
> +import renderModal from '../templates/pop-up.hbs';
путь с одной точкой

2023-08-06 20:29 UTC, Morifer79 commented on src/js/pop-up.js
> +import {fetchBooks} from '../js/api.js'
путь с одной точкой

2023-08-06 20:29 UTC, Morifer79 commented on src/js/pop-up.js
> +    barnesAndNobleSrcX2: require('../images/modal/image-3@2x.png'),
все пути с одной точкой

2023-08-06 21:30 UTC, Morifer79 approved these changes

2023-08-06 21:32 UTC, merged