Feature allcategories support
Morifer79/code-jedi-project-02 pull request #6
Opened 2023-08-05 17:21 UTC by Vadym-Ivanenko

2023-08-05 23:37 UTC, Morifer79 requested changes

2023-08-05 23:37 UTC, Morifer79 commented on src/css/support.css
> +    transition: color 250ms cubic-bezier(0.4, 0, 0.2, 1)
в style.css уже есть переменная для  transition - используй её

2023-08-05 23:37 UTC, Morifer79 commented on src/css/support.css
> +        line-height: 24px;
line-height указываем в виде коэффициента... в твоём случае это 1.33

2023-08-05 23:37 UTC, Morifer79 commented on src/css/support.css
> +        line-height: 24px;
то же самое... 
line-height / font-size = коэффициент

2023-08-05 23:37 UTC, Morifer79 commented on src/css/support.css
> +    box-shadow: 0px 10px 10px 0px rgba(245, 245, 247, 0.10);
новый синтаксис...
не критично, но 0.10 записываем просто как .1

2023-08-05 23:37 UTC, Morifer79 commented on src/css/support.css
> +    line-height: 24px;
переведи в коэффициент

2023-08-05 23:37 UTC, Morifer79 commented on src/css/support.css
> +        line-height: 28px;
снова коэффициент...

2023-08-05 23:37 UTC, Morifer79 commented on src/js/allCategories-markup.js
> +export default function categoriesListMarkup(data) {
в самом начале договаривались, чтобы дефолтных экспортов не было...
применяем только именованные

2023-08-05 23:37 UTC, Morifer79 commented on src/js/allCategories-render.js
> +export default async function getBookAPI(type, value = '') {
дефолтные экспорты не применяем...

2023-08-05 23:37 UTC, Morifer79 commented on src/js/support-list.js
> +import sergiyPrytula from '../images/06.png';
можешь оставить так, но что мы выигрываем потерей 9 строк - я так и не понял)

2023-08-06 09:24 UTC, Vadym-Ivanenko commented on src/css/support.css
> +    box-shadow: 0px 10px 10px 0px rgba(245, 245, 247, 0.10);
Вибач , не розумію що маєш на увазі, можливо ткрлю. Поясни, що маєш на увазі

2023-08-06 23:44 UTC, Morifer79 approved these changes

2023-08-06 23:44 UTC, Morifer79 commented on src/css/support.css
> +    box-shadow: 0px 10px 10px 0px rgba(245, 245, 247, 0.10);
вот как должно быть box-shadow: 0 10px 10px 0 rgba(245, 245, 247, .1);

2023-08-06 23:44 UTC, merged